# PROUDCT CRUD OPERATION #

# POST /products
POST http://localhost:3010/api/v1/products HTTP/1.1
Content-Type: application/json

{
  "title": "Best Sneaker Collection 5",
  "description": "Test Product deescription goes here",
  "category": "Sneakers",
  "variants": ["red", "black", "blue"],
  "sizes" : ["41", "42", "45"],
  "image":"https://source.unsplash.com/1600x900/?sneaker",
  "price" : 100,
  "quantity": 99.55
}

###
#GET /products
GET http://localhost:3010/api/v1/products HTTP/1.1

###
#GET /:productId
GET http://localhost:3010/api/v1/products/619f6c058be5d2ff615802f7 HTTP/1.1

###
# PUT /:productId
PUT http://localhost:3010/api/v1/products/619f6c058be5d2ff615802f7 HTTP/1.1
Content-Type: application/json

{
  "title": "Updated v1 - Test Product 2",
  "description": "Updated v1 - Test Product 2 description",
  "category": "Updated v1 - testCategory",
  "variants": ["red", "blue"],
  "sizes" : ["m", "xl"],
  "image":"https://source.unsplash.com/1600x900/?phone",
  "price" : 500,
  "quantity": 2000
}

###
# DELETE /:productId
DELETE http://localhost:3010/api/v1/products/619f6c058be5d2ff615802f7

###
# USER CRUD OPERATION #

# POST /register
POST http://localhost:3010/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Khan Fayjul test",
  "email": "khantest@email.com",
  "password": "123456",
  "address": "123 North Street, CA-0000"
}

###
# POST /login
POST http://localhost:3010/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "khan123@email.com",
  "password": "123456"
}

###
# GET /users
GET http://localhost:3010/api/v1/users HTTP/1.1

###
# GET /users/:userId
GET http://localhost:3010/api/v1/users/61ae64825622facdeadbf1ca HTTP/1.1

###
# PUT /users/register
PUT http://localhost:3010/api/v1/users/61a004293afa253bf69c220c HTTP/1.1
Content-Type: application/json

{
  "name": "Khan Fayjul test",
  "email": "KHAN6emailtest@gmail.com",
  "password": "12345678",
  "avatar":"https://source.unsplash.com/1600x900/?man",
  "address": "123 North Street, CA-0000",
  "isAdmin" : false,
  "isBanned":true
}

###
# DELETE /users/register
DELETE  http://localhost:3010/api/v1/users/61a004293afa253bf69c220c HTTP/1.1

###
# Cart CRUD OPERATION #

# POST /cart
POST http://localhost:3010/api/v1/carts/ HTTP/1.1
Content-Type: application/json

{
  "userId": "61a202a146878b6974306f2a",
  "products":[
    {
      "productId": "61a2027246878b6974306f26",
      "quantity": 5
    }
  ]
}

###
#GET /carts
GET http://localhost:3010/api/v1/carts HTTP/1.1

###
#GET /:cartId
GET http://localhost:3010/api/v1/carts/61a828ffd0242e1ecf55350a HTTP/1.1

###
# PUT /:cartId
PUT http://localhost:3010/api/v1/carts/61a828ffd0242e1ecf55350a HTTP/1.1
Content-Type: application/json
# could not update withoutt the userId
{
  "userId": "61a202c946878b6974306f2c",
  "products":[
    {
      "productId": "61a826bc29afee1b3587e90c",
      "quantity": 10
    },
    {
      "productId": "61a38298d63213808a1af441",
      "quantity": 100
    }
  ]
}

###
# DELETE /:productId
DELETE http://localhost:3010/api/v1/carts/61a828ffd0242e1ecf55350a


###
# Order CRUD OPERATION #

# POST /orders
POST http://localhost:3010/api/v1/orders/ HTTP/1.1
Content-Type: application/json

{
  "userId": "61a202a146878b6974306f2a",
  "products":[
    {
      "productId": "61a2027246878b6974306f26",
      "quantity": 5
    }
  ],
  "amount": 200
}

###
#GET /orders
GET http://localhost:3010/api/v1/orders HTTP/1.1

###
#GET /:orderId
GET http://localhost:3010/api/v1/orders/61a83bdba5e91b3975084111 HTTP/1.1

###
# PUT /:orderId
PUT http://localhost:3010/api/v1/orders/61a83bdba5e91b3975084111 HTTP/1.1
Content-Type: application/json

{
  "userId": "61a202a146878b6974306f2a",
  "products":[
    {
      "productId": "61a2032146878b6974306f3e",
      "quantity": 500
    }
  ],
  "amount": 2000
}

###
# DELETE /:orderId
DELETE http://localhost:3010/api/v1/orders/61a83bdba5e91b3975084111